<div id="form_container">
    <form id="form_559839" class="appnitro"  method="post" action="">
        <ul >
            <li id="li_1" >
                <label class="description" for="element_1">Name </label>
                <span>
                    <input id="element_1_1" name= "element_1_1" class="element text" maxlength="255" size="7" value=""/>
                    <label>First</label>
                </span>
                <span>
                    <input id="element_1_2" name= "element_1_2" class="element text" maxlength="255" size="12" value=""/>
                    <label>Last</label>
                </span> 
            </li>
            <li id="li_6" >
                <label class="description" for="element_6">Email </label>
                <div>
                    <input id="element_6" name="element_6" class="element text medium" type="text" maxlength="255" value=""/> 
                </div> 
            </li>
            <li id="li_2" >
                <label class="description" for="element_2">Date </label>
                <span>
                    <input id="element_2_1" name="element_2_1" class="element text" size="1" maxlength="2" value="" type="text"> /
                    <label for="element_2_1">MM</label>
                </span>
                <span>
                    <input id="element_2_2" name="element_2_2" class="element text" size="1" maxlength="2" value="" type="text"> /
                    <label for="element_2_2">DD</label>
                </span>
                <span>
                    <input id="element_2_3" name="element_2_3" class="element text" size="4" maxlength="4" value="" type="text">
                    <label for="element_2_3">YYYY</label>
                </span>
            
                <span id="calendar_2">
                    <img id="cal_img_2" class="datepicker" src="images/form/calendar.gif" alt="Pick a date.">   
                </span>
                <script type="text/javascript">
                    Calendar.setup({
                    inputField   : "element_2_3",
                    baseField    : "element_2",
                    displayArea  : "calendar_2",
                    button       : "cal_img_2",
                    ifFormat     : "%B %e, %Y",
                    onSelect     : selectDate
                    });
                </script>
                 
            </li>
            <li id="li_3" >
                <label class="description" for="element_3">Time </label>
                <span>
                    <input id="element_3_1" name="element_3_1" class="element text " size="2" type="text" maxlength="2" value=""/> : 
                    <label>HH</label>
                </span>
                <span>
                    <input id="element_3_2" name="element_3_2" class="element text " size="2" type="text" maxlength="2" value=""/> : 
                    <label>MM</label>
                </span>
                <span>
                    <input id="element_3_3" name="element_3_3" class="element text " size="2" type="text" maxlength="2" value=""/>
                    <label>SS</label>
                </span>
                <span>
                    <select class="element select" style="width:4em" id="element_3_4" name="element_3_4">
                        <option value="AM" >AM</option>
                        <option value="PM" >PM</option>
                    </select>
                    <label>AM/PM</label>
                </span> 
            </li>
            <li id="li_4" >
                <label class="description" for="element_4">Number of Guests </label>
                <div>
                    <input id="element_4" name="element_4" class="element text medium" type="text" maxlength="255" value=""/> 
                </div> 
            </li>
            <li class="buttons">
                <input type="hidden" name="form_id" value="559839" />
                <input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
            </li>
        </ul>
    </form> 
    <div id="footer">
        Generated by <a href="http://www.phpform.org">pForm</a>
    </div>
</div>